version: "3"
services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zoiz
      PORT: 5432
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      - "PGADMIN_DEFAULT_EMAIL=user@domain.com"
      - "PGADMIN_DEFAULT_PASSWORD=SuperSecret"
  zoiz-front:
    image: zoiz-front:latest
    environment:
      PORT: 4200
      PROXY_API: http://zoiz-back:8080/
    ports:
      - 4200:4200
  zoiz-back:
    image: zoiz-back:latest
    depends_on: 
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/zoiz
      - PORT=8080
    ports:
      - 8080:8080